### PR TITLE
Subtotal done

### PR DESCRIPTION
**Pull request by Upasana23-hub**
Hi @girianimesh ,
Please approve & merge the PR. I have completed the "Cart-Total" portion. Next Step to be achieved is not to display blank cart page when cart is empty.

FYI:
Screenshot 2024-03-24 082341

REF: https://github.com/Upasana23-hub/E-COMMERCE/pull/44
CC: @AnkitDhar

### CODE REVIEW

**Comment by Subhratanu** [comment]
Hi @Upasana23-hub ,

The following PR can't be merge as the logic is wrong. If you see you have two items in your cart that having a total value 21955 but it's displaying as 64987.

Please refer the logic one more time & raise a fresh PR.

Closing this PR.

Cc: @girianimesh @AnkitDhar

**Comment by Subhratanu** [comment]
Closing the PR

**Comment by Subhratanu** [comment]
Hi @Upasana23-hub ,

Could you please attach some of the reference screenshot?

Attach in this way, if you increment the counter the total value increments & when you are removing or Decrementing product count then total is decrementing.

**Comment by Upasana23-hub** [comment]
Hi @Subhratanu ,
I have corrected the logic of the total price. Please review and merge the PR. And revert if any more changes are needed .
FYI: 
Screenshot 2024-03-24 103625
Screenshot 2024-03-24 103720
Screenshot 2024-03-24 103757

CC @girianimesh @AnkitDhar

**Review by Subhratanu — APPROVED** [review]
Hi @Upasana23-hub ,

Merged the PR.

Thanks!

**Pull request merged**
