### PR TITLE
changes in mock data

### PR DESCRIPTION
**Pull request by Upasana23-hub**
Hi @AnkitDhar ,
I have changed some part of mock data as per your problem. Please review and merge this PR. Revert it if any changes needed.
Thanks! 
CC: @girianimesh @Subhratanu

### CODE REVIEW

**Review by Subhratanu — CHANGES_REQUESTED** [review]
Hi @Upasana23-hub 

It's not a correct way to resolve the issue, you are not allowed to changed mockdata.json . Please find some alternative way to solve the issue.

**Comment by Upasana23-hub** [comment]
Hi @Subhratanu ,
Actually there were some mistakes in mock data from the beginning. Without changing this file , there will be some problems in searching .

**Comment by AnkitDhar** [comment]
Hi @Subhratanu ,
In that previous pull request there were issues in search and some cards were fully blanked by mistake . So changes in the mock data is required .
Thanks!
CC : @girianimesh @Upasana23-hub

**Comment by Subhratanu** [comment]
Hi @Upasana23-hub / @AnkitDhar ,

We are no way in the position to do the changes in mockdata. It would be better if you scope this as a issue in QA.

Hence closing the PR.

Thanks !

**Pull request closed without merging**
